import joi from 'joi'
export const email = joi.string().pattern(new RegExp('@gmail.com$')).required()
export const password = joi.string().required()
export const confirmPassword = joi.string().required()
export const phone = joi.string().required()
export const name= joi.string().required()
export const image_url= joi.string().allow('', null)
export const specialty_id= joi.string().allow('', null)
export const rating= joi.number().required()
export const price= joi.number().required()
export const description= joi.string().required()
export const shop_id = joi.string().allow(null, '')
